### ISSUE TITLE
`icestream` FV doesn't converge (yet)

### ISSUE THREAD

**Issue by AdrienWehrle** [AdrienWehrle/diuca#16]
The problem `icestream_fv_3d_SI.i` is getting very close to the problem I want to run for my project (which is exciting!). I'm currently working with [this input file](https://github.com/AdrienWehrle/diuca/blob/PR_icestreamFV/problems/icestream_fv_3d_SI.i) that I work with in https://github.com/AdrienWehrle/diuca/pull/6.

```
Framework Information:
MOOSE Version:           git commit 0b297bbb93 on 2024-02-15
LibMesh Version:         
PETSc Version:           3.20.3
SLEPc Version:           3.20.1
Current Time:            Wed Feb 28 09:54:08 2024
Executable Timestamp:    Tue Feb 27 19:26:38 2024

Parallelism:
  Num Processors:          1Reach convergence in
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          3
  Spatial Dimension:       3
  Nodes:                   41769
  Elems:                   4712
  Num Subdomains:          3

Nonlinear System:
  Num DOFs:                18848
  Num Local DOFs:          18848
  Variables:               { "vel_x" "vel_y" "vel_z" "pressure" } 
  Finite Element Types:    "MONOMIAL" 
  Approximation Orders:    "CONSTANT" 

Execution Information:
  Executioner:             Transient
  TimeStepper:             ConstantDT
  TimeIntegrator:          ImplicitEuler
  Solver Mode:             Preconditioned JFNK
  PETSc Preconditioner:    lu 


Time Step 0, time = 0

Time Step 1, time = 3.1536e+06, dt = 3.1536e+06
Currently Executing
    Computing Initial Residual
      Computing Residual
        Finished Computing Rhie-Chow coefficients                                        [  1.12 s] [  461 MB]
      Finished Computing Residual                                                        [  1.64 s] [  528 MB]
    Finished Computing Initial Residual                                                  [  1.64 s] [  528 MB]
    |residual|_2 of individual variables:
                   vel_x:    2424.59
                   vel_y:    0
                   vel_z:    487678
                   pressure: 29484.2
 0 Nonlinear |R| = 4.885749e+05
    Computing Jacobian.....                                                              [ 33.77 s] [  626 MB]
  Linear solve did not converge due to DIVERGED_PC_FAILED iterations 0
                 PC failed due to FACTOR_NUMERIC_ZEROPIVOT 
Nonlinear solve did not converge due to DIVERGED_FNORM_NAN iterations 0
 Solve Did NOT Converge!
  Finished Solving                                                                       [ 49.94 s] [  626 MB]
Aborting as solve did not converge

Time Step 1, time = 1.5768e+06, dt = 1.5768e+06
    |residual|_2 of individual variables:
                   vel_x:    2424.59
                   vel_y:    0
                   vel_z:    487678
                   pressure: 29484.2
 0 Nonlinear |R| = 4.885749e+05
  Linear solve did not converge due to DIVERGED_PC_FAILED iterations 0
                 PC failed due to FACTOR_NUMERIC_ZEROPIVOT 
Nonlinear solve did not converge due to DIVERGED_FNORM_NAN iterations 0
 Solve Did NOT Converge!
  Finished Solving                                                                       [ 18.01 s] [  626 MB]
Aborting as solve did not converge

Time Step 1, time = 788400, dt = 788400
    |residual|_2 of individual variables:
                   vel_x:    2424.59
                   vel_y:    0
                   vel_z:    487678
                   pressure: 29484.2
 0 Nonlinear |R| = 4.885749e+05
  Linear solve did not converge due to DIVERGED_PC_FAILED iterations 0
                 PC failed due to FACTOR_NUMERIC_ZEROPIVOT 
Nonlinear solve did not converge due to DIVERGED_FNORM_NAN iterations 0
 Solve Did NOT Converge!
  Finished Solving                                                                       [ 21.07 s] [  626 MB]
Aborting as solve did not converge

Time Step 1, time = 394200, dt = 394200
    |residual|_2 of individual variables:
                   vel_x:    2424.59
                   vel_y:    0
                   vel_z:    487678
                   pressure: 29484.2
 0 Nonlinear |R| = 4.885749e+05
  Linear solve did not converge due to DIVERGED_PC_FAILED iterations 0
                 PC failed due to FACTOR_NUMERIC_ZEROPIVOT 
Nonlinear solve did not converge due to DIVERGED_FNORM_NAN iterations 0
 Solve Did NOT Converge!
  Finished Solving                                                                       [ 20.01 s] [  626 MB]
Aborting as solve did not converge

Time Step 1, time = 197100, dt = 197100
    |residual|_2 of individual variables:
                   vel_x:    2424.59
                   vel_y:    0
                   vel_z:    487678
                   pressure: 29484.2
 0 Nonlinear |R| = 4.885749e+05
```

At the moment it doesn't reach convergence with LU nor with SVD. Let's try and understand why and give a chance to other strategies.

I'll try and investigate e.g. velocity scaling since the mesh is of a different scale now (we're working with 1km long 100m thick system in `iceslab`, now we have a glacier geometry that's closer to reality, here 10km long, minimum 500m thick).

**Comment by AdrienWehrle** [comment]
Won't be investigated as long as https://github.com/AdrienWehrle/diuca/issues/13 is not solved, and the latter is currently on hold (see issue).

**Comment by AdrienWehrle** [comment]
I now reach convergence here not with air above water at the front too (earlier I was converging only with ice above water), as follows 
```
[ocean_pressure]
    type = ParsedFunction
    expression = 'if(z < 0, 1e5 -1028 * 9.81 * z, 1e5)'
  []
```
The problem now is that as soon as I refine the grid (because it's very coarse now), I can't reach convergence anymore. See below. It doesn't diverge but it seems like it would take hours to get down to e-7 or so. Did you see convergence stopping with mesh refinement in the past, @GiudGiud?

```
MOOSE Version:           git commit cee3f610f9 on 2024-01-25
LibMesh Version:         
PETSc Version:           3.20.3
SLEPc Version:           3.20.1
Current Time:            Mon Mar 18 15:51:36 2024
Executable Timestamp:    Mon Mar 18 11:07:07 2024

Parallelism:
  Num Processors:          1
  Num Threads:             12

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          3
  Spatial Dimension:       3
  Nodes:                   3213
  Elems:                   2496
  Num Subdomains:          2

Nonlinear System:
  Num DOFs:                9984
  Num Local DOFs:          9984
  Variables:               { "vel_x" "vel_y" "vel_z" "pressure" } 
  Finite Element Types:    "MONOMIAL" 
  Approximation Orders:    "CONSTANT" 

Execution Information:
  Executioner:             Transient
  TimeStepper:             ConstantDT
  TimeIntegrator:          ImplicitEuler
  Solver Mode:             Preconditioned JFNK
  PETSc Preconditioner:    lu 

Time Step 0, time = 0

Time Step 1, time = 3.1536e+06, dt = 3.1536e+06
Currently Executing
    Computing Initial Residual
      Computing Residual
        Finished Computing Rhie-Chow coefficients                                        [  0.11 s] [  435 MB]
      Finished Computing Residual                                                        [  0.80 s] [  513 MB]
    Finished Computing Initial Residual                                                  [  0.80 s] [  513 MB]
    |residual|_2 of individual variables:
                   vel_x:    6.08175e+06
                   vel_y:    0
                   vel_z:    3.47473e+07
                   pressure: 1.46511e+06
 0 Nonlinear |R| = 3.530597e+07
      0 Linear |R| = 3.530597e+07
      1 Linear |R| = 3.052867e+07
      2 Linear |R| = 3.021455e+07
      3 Linear |R| = 3.021226e+07
      4 Linear |R| = 3.021217e+07
      5 Linear |R| = 3.015609e+07
      6 Linear |R| = 3.013134e+07
      7 Linear |R| = 3.010398e+07
      8 Linear |R| = 3.010249e+07
      9 Linear |R| = 3.008850e+07
     10 Linear |R| = 3.005383e+07
     11 Linear |R| = 3.005175e+07
     12 Linear |R| = 3.003207e+07
     13 Linear |R| = 3.001786e+07
     14 Linear |R| = 3.001285e+07
     15 Linear |R| = 2.998013e+07
     16 Linear |R| = 2.996114e+07
     17 Linear |R| = 2.996067e+07
     18 Linear |R| = 2.995449e+07
     19 Linear |R| = 2.995352e+07
```

An example of refinement I used is e.g.:
```
[Mesh]

  [channel]
    type = FileMeshGenerator
    file = mesh_icestream.e
  []

  # delete sediment block for now (below bedrock)
  [delete_sediment_block]
    type = BlockDeletionGenerator
    input = channel
    block = '3'
  []
  
  [frontal_zone]
    type = SubdomainBoundingBoxGenerator
    input = 'delete_sediment_block'
    block_id = 10
    bottom_left = '20000 -1000 -3000'
    top_right = '19000  15000 3000'
  []
  
  [refined_front]
    type = RefineBlockGenerator
    input = "frontal_zone"
    block = '10'
    refinement = '1'
    enable_neighbor_refinement = true
    max_element_volume = 1e100
  []
[]
```

But I also tried recreating a finer mesh (on the entire domain), and ended up with similar convergence issues.

**Comment by AdrienWehrle** [comment]
The convergence issue can be reproduced running this input file: https://github.com/AdrienWehrle/diuca/blob/PR_IIepsmin_rampup/problems/icestream_fv_3d_SI_autorampup.i

**Comment by AdrienWehrle** [comment]
Updates on trials:

- change element aspect ratios and shapes didn't improve convergence
- changing the velocity scaling didn't improve convergence
- trying a vast range of `II_eps_min` and rampup pace didn't improve convergence
- it seems independent of the pressure boundary at the front (issues on convergence with both ice and air)

**Comment by GiudGiud** [comment]
Can you try to refine the mesh outside of MOOSE?

**Comment by AdrienWehrle** [comment]
> Can you try to refine the mesh outside of MOOSE?

yes I tried this with my mesh generator outside of MOOSE but I get similar results (struggles to converge)...

**Comment by GiudGiud** [comment]
Can you keep track of mesh-sizes vs best II_eps_min we can reach? Maybe there's a pattern, something like a CFL criterion we should be aware of for high viscosity flows

**Comment by AdrienWehrle** [comment]
CFL condition violation is definitely a thing in glacier modeling, that's also why I checked a wide range of `II_eps_min` and mesh resolutions, but I'll investigate more with this in mind.

**Comment by AdrienWehrle** [comment]
Interesting, now I added a few more elements in x increasing the resolution from 933m to 758m and as expected, it doesn't converge anymore. Then I tried changing the `II_eps_min` automatic rampup and started at 1e-6 instead of the 1e-10 before, and it does reach steady state at a similarly low final `II_eps_min` value where it doesn't constrain the system anymore. 

I'll try and get a relation with several cases as you suggested!

**Comment by AdrienWehrle** [comment]
It feels like we could use the CFL number to constrain the initial `II_eps_min`. Or maybe we can simply keep it rather high for all cases. I'm investigating.

**Comment by AdrienWehrle** [comment]
WIP

All `II_eps_min` rampups used here follow `expression = 'initial_II_eps_min * exp(-(t-_dt) * 1e-6)'` and ended up converging on `II_eps_min` values that don't constrain the system anymore.

| CFL number  | `initial_II_eps_min` |
| ------------- | ------------- |
| 3000 * 0.01 / 933 = 0.0321  | 1e-10  |
| 3000 * 0.01 / 758 = 0.0396  | 1e-06  |

**Comment by AdrienWehrle** [comment]
Very interesting observation here. If I reduce dt on the last simulation reported above (FV, refinement at the front to reach an x-resolution below 500m), I fall back on the bad solve we get with the FE setup, that might tell us a bit about why the latter is actually failing!

![image](https://github.com/AdrienWehrle/diuca/assets/44843368/b8694392-f6ef-46d5-999b-595e67dd6501)

**Comment by AdrienWehrle** [comment]
@GiudGiud, it feels like this observation might be important for us to potentially understand what's wrong in the FE setup. The good solution right above is only reached with very low `II_eps_min` (like 1e-100!!) which might mean we still constrain it too much in the FE setup which forces it to reach an unphysical solution (second to last screenshot).

**Comment by AdrienWehrle** [comment]
If I decrease the timestep by a factor of 10 (dt = 0.001; expected CLF = 3000 * 0.001 / 467 = 0.0064), the switch in solution doesn't happen within the first 100 timesteps (if it's directly related, maybe timestep=200 since timestep is 10 times lower).

If I increase the timestep by a factor of 5 (dt = 0.05; expected CLF = 3000 * 0.05 / 467 = 0.3212, the switch in solution starts at timestep = 6!

**Comment by GiudGiud** [comment]
This is probably the rigid body / null space item that Jed was mentioning. We should try to use the MOOSE options to remove it and/or implement something to ban that bad solution

**Comment by AdrienWehrle** [comment]
> This is probably the rigid body / null space item that Jed was mentioning. We should try to use the MOOSE options to remove it and/or implement something to ban that bad solution

It looks like it's possible to move away from it to reach the right solution playing with the CLF condition, i.e. playing with the timestep and spatial resolution, but it would for sure make everything more stable and less in need for tuning if we could just ban it!
