### ISSUE TITLE
Sediment/ice coupling not working in `icestream` FV

### ISSUE THREAD

**Issue by AdrienWehrle** [AdrienWehrle/diuca#29]
In `icestream_fv_3d_SI_ru_slip.i` is implemented a sediment layer with controllable thickness and constant viscosity as a function of the sediment thickness and a slipperiness coefficient (a different formulation from the one I initially used, this one being much simpler). At the moment in main, the sediment layer in 50m thick with an equivalent viscosity of 1e8 Pas. A null Dirichlet BC is set at the base of the sediments, so that the sediments are being deformed by the glacier motion on top of it.

The velocity in the sediment layer (`block_0`) is wrong. `vel_z` of ~ - 0.1 m.s-1 showing the sediments are clearly collapsing while there is a null dirichlet BC in z (and x and y) at their base... At the same time, `vel_x` and `vel_y` of 0 while they should be affected by the glacier motion in x... 
See below `vel_x` and `vel_z` in the sediment layer.

![Screenshot from 2024-04-04 15-17-27](https://github.com/AdrienWehrle/diuca/assets/44843368/04110462-cf1e-41e3-9d97-2ecb292ab999)
![Screenshot from 2024-04-04 15-17-21](https://github.com/AdrienWehrle/diuca/assets/44843368/f3f341fd-7afe-4090-93c2-d2f4cbe8d04a)

The glacier system solves nicely as if there was no slip at the base, while the whole layer is actually sinking super fast... 
See below `vel_x` on the glacier block.

![image](https://github.com/AdrienWehrle/diuca/assets/44843368/63f54b15-46fc-4f1f-9aa7-e72fcbd42133)

Any idea  why this might be happening @GiudGiud?  I thought this could come from boundary penetration that we discussed a few weeks ago, considering the high overburden pressure from the glacier having a much higher viscosity than the sediments. But in this case 1) the glacier would also sink down in reaction, which is not the case and 2) the negative velocity in z is beyond any physical reaction to overburden pressure...

I tried different inlet and outlet BCs in the sediments but it always ends up in the same situation, or doesn't converge.

**Comment by AdrienWehrle** [comment]
There is a `INSFVNoSlipWallBC` on the bottom side of that layer of sediments:

https://github.com/AdrienWehrle/diuca/blob/73b772aaee4ffb41a874b630306d2b83222b15b5/problems/icestream_fv_3d_SI_ru_slip.i#L344-L361 

and no BC at the interface between ice and sediments. Maybe I'm doing something wrong when I stitch the two blocks after I create the sediment layer but I basically copy/pasted the example from MOOSE:

https://github.com/AdrienWehrle/diuca/blob/73b772aaee4ffb41a874b630306d2b83222b15b5/problems/icestream_fv_3d_SI_ru_slip.i#L84-L109

I used the whole sequence of objects instead of the wrapped one to have access to the name of the new boundary.

**Comment by GiudGiud** [comment]
This seems fine to me. Do the results improve / vary with mesh refinement?
Could you simulate a 2D 2-region slice and see if you can see the problem there?

**Comment by AdrienWehrle** [comment]
I'm back into ice viscous flow modeling here. :)

I wasn't using `MeshExtruderGenerator` properly so that the bottom boundaries were not set at the right place (initially at the top of the sediment layer instead of the bottom).
