### ISSUE TITLE
Missing parameter in `icestream` FV

### ISSUE THREAD

**Issue by AdrienWehrle** [AdrienWehrle/diuca#7]
for now `problems/icestream_fv_3d_SI.i` proposed in https://github.com/AdrienWehrle/diuca/pull/6 gives

```
*** ERROR ***
[local_path]/projects/diuca/problems/icestream_fv_3d_SI.i:252: missing required parameter 'Functions/FunctorMaterials/type'
	Doc String: "A string representing the Moose Object that will be built by this Action"
```

**Comment by GiudGiud** [comment]
It shouldnt be this `Functions/FunctorMaterials/type`

Both Functions and FunctorMaterials are both top-level blocks

**Comment by AdrienWehrle** [comment]
Thanks, I had an unclosed block...!
