### ISSUE TITLE
Add `FVSedimentMaterial`

### ISSUE THREAD

**Issue by AdrienWehrle** [AdrienWehrle/diuca#8]
We need this object to have a better representation of basal slip in case we use FV instead of FE in the final setup. 

I'll write it shortly based on `FVIceMaterial`.

**Comment by AdrienWehrle** [comment]
compilation gives 
```
[local_path]/diuca/src/materials/FVSedimentMaterialSI.C:83:15: error: 'viscosity' was not declared in this scope
   83 |  ADReal eta = viscosity;
```

I need to access the current `viscosity` of the material while this very value is being returned as a `FunctorProperty`. In AD I could just call `_viscosity[_qp]` but need to find the way to do it in FV. Maybe @GiudGiud can help here?

**Comment by GiudGiud** [comment]
Is it supposed to be a constant?

**Comment by AdrienWehrle** [comment]
> Is it supposed to be a constant? viscosity is defined later in that source file

No but viscosity at timestep t is needed to compute the one at timestep t+1

**Comment by AdrienWehrle** [comment]
Thanks a lot it's compiling without error now. I had to call `StateArg` and `SolutionIterationType` through `Moose::` though, maybe there are two ways to call them? (either import header or call `Moose::`?

**Comment by GiudGiud** [comment]
Ok this is normal they are in the Moose namespace
