### ISSUE TITLE
Use `SedimentMaterial` in `icestream`

### ISSUE THREAD

**Issue by AdrienWehrle** [AdrienWehrle/diuca#9]
At the moment the `icestream` base is ice (with a null Dirichlet on velocity). Once either/both `icestream` FV and FE converge, add `SedimentMaterial` first with constant velocity, then with a velocity as a function of the second invariant and friction coeffiicent (already implemented in `ADSedimentMaterial` but kept constant for now).

**Comment by AdrienWehrle** [comment]
Now working on this with the FV setup here https://github.com/AdrienWehrle/diuca/pull/26

So now I have two different viscosities `mu` and densities `rho`, for the ice and the sediments respectively. To my understanding and taking the example of `INSFVMomentumAdvection` which is as follows when there's only ice:

```
[u_advection]
    type = INSFVMomentumAdvection
    variable = vel_x
    advected_interp_method = ${advected_interp_method}
    velocity_interp_method = ${velocity_interp_method}
    rho = ${rho}
    momentum_component = 'x'
[]
```

I'd need to do the following for ice + sediment (and for all other kernels):

```
[u_advection_ice]
    type = INSFVMomentumAdvection
    variable = vel_x
    advected_interp_method = ${advected_interp_method}
    velocity_interp_method = ${velocity_interp_method}
    rho = ${rho_ice}
    momentum_component = 'x'
[]
  [u_advection_sediment]
    type = INSFVMomentumAdvection
    variable = vel_x
    advected_interp_method = ${advected_interp_method}
    velocity_interp_method = ${velocity_interp_method}
    rho = ${rho_sediment}
    momentum_component = 'x'
[]
```

Does that make sense to you @GiudGiud? I've scrapped MOOSE input files trying to find an example with multiple materials in different blocks but I couldn't find a setup I could use a template for my use case here. 

Thank you.

**Comment by GiudGiud** [comment]
I would recommend defining a 'rho' and a 'mu' functor that are this type and change for ice and sediment
https://mooseframework.inl.gov/source/functormaterials/PiecewiseByBlockFunctorMaterial.html

then you can just use a single kernel

**Comment by AdrienWehrle** [comment]
> I would recommend defining a 'rho' and a 'mu' functor that are this type and change for ice and sediment https://mooseframework.inl.gov/source/functormaterials/PiecewiseByBlockFunctorMaterial.html
> 
> then you can just use a single kernel

Great thanks a lot, I'll work on this!
